### ISSUE TITLE
Package all new optional deps like libfreeaptx of pipewire

### ISSUE THREAD

**Issue by rxrbln** [rxrbln/t2sde#148]
like:

Run-time dependency libmysofa found: NO (tried pkgconfig and cmake)
Run-time dependency webrtc-audio-processing-1 found: NO (tried pkgconfig and cmake)
Run-time dependency webrtc-audio-processing found: NO (tried pkgconfig and cmake)
Library intl found: NO
Run-time dependency lilv-0 found: NO (tried pkgconfig and cmake)
Run-time dependency libffado found: NO (tried pkgconfig and cmake)
Program gstack found: NO
Run-time dependency ldacbt-enc found: NO (tried pkgconfig and cmake)
Run-time dependency ldacbt-abr found: NO (tried pkgconfig and cmake)
Run-time dependency libfreeaptx found: NO (tried pkgconfig and cmake)
Run-time dependency lc3plus found: NO (tried pkgconfig and cmake)

**Comment by N0T4G** [comment]
Done.
Everything is available as of revision r68782.
