### ISSUE TITLE
Why Not Self Promote

### ISSUE THREAD

**Issue by juanpc2018** [rxrbln/t2sde#164]
https://www.youtube.com/watch?v=MTkPWrG0zig&t=1515s

i do Not recommend becoming Popular Distro, 
Govs. start to panic, when there is something they cannot control,
infiltrate, and alter with back doors.

there is [plenty](https://www.facebook.com/GreatLearningOfficial/videos/the-university-of-texas-at-austin-a-top-ranked-university-in-ai-ml/431602474212110/) of [missing developers](https://www.youtube.com/watch?v=hAx6mYeC6pY) -> [:)](https://en.wikipedia.org/wiki/Smiley_face_murder_theory)

for example Odysee.com / [LBRY](https://en.wikipedia.org/wiki/LBRY) network was taken over, to alter the code "re-write in Go" 
to connect everything with [DR Ai](https://en.wikipedia.org/wiki/Digital_Reasoning) and [BR Ai](https://en.wikipedia.org/wiki/Aladdin_(BlackRock))
and China [Ai](https://en.wikipedia.org/wiki/Mass_surveillance_in_China)
China Ai is just a Redundat System.

[Everything i write here also](https://www.youtube.com/watch?v=BRE_nJf9RK0) LOL

it has 160 Billion Neurons, Twice of human, but most are used for the [1000 eyes](https://www.youtube.com/watch?v=Plr7_SAuB6g&t=27s) -> [LOL](https://www.youtube.com/watch?v=cxrNA1c8Zpk&t=12s)

**Comment by rxrbln** [comment]
thanks for your input
