### ISSUE TITLE
ksvg.desc under packages/kde/kdiagram

### ISSUE THREAD

**Issue by AMDmi3** [rxrbln/t2sde#173]
https://github.com/rxrbln/t2sde/commit/f4503be3a147d0970193aa4f1b8899bd9479a725 has added `ksvg` recipe under `packages/kde/kdiagram` dir. Is this correct? Because
- There already is `packages/kde/ksvg`: https://github.com/rxrbln/t2sde/tree/main/package/kde/ksvg
- Packages browser is messed up, containing two entries for kdiagram in the [listing](https://t2sde.org/packages/kdiagram), which point to the same [page](https://t2sde.org/packages/kdiagram), which mentions both kdiagram and ksvg files.

**Comment by rxrbln** [comment]
thanks you for the report, it probably slipped with some form of CLI typo when copied from the ksvg pkg:
Committed revision 69273.
