### ISSUE TITLE
Where to buy or download full songs about Unix standards war clans etc?

### ISSUE THREAD

**Issue by xet7** [rxrbln/t2sde#180]
Hi Übercoder,
where it's possible to buy or download full songs about Unix standards war clans etc? And other songs of this band, what band is this? Beginning of that song is at the beginning of this video. Also, at end of this video is song about T2 SDE.

https://www.youtube.com/watch?v=TymtTjinN7o

**Comment by rxrbln** [comment]
https://suno.com/song/26939149-a0db-442e-a6b8-c7c2b02adb8e
https://suno.com/song/82d7e864-d6b0-42e2-a869-ec09e6176c1d
donations welcome: https://t2sde.org/support ;-)
