### ISSUE TITLE
/usr/bin/autoconf: line 5: /usr/bin/perl: No such file or directory

### ISSUE THREAD

**Issue by eneiasramos** [rxrbln/t2sde#184]
I'm trying to run the autoconf command but I'm getting an error saying the perl command was not found:

/usr/bin/autoconf: line 5: /usr/bin/perl: No such file or directory

![image](https://github.com/user-attachments/assets/d3bd754c-e2f8-42c8-812f-3b620173c89d)

**Comment by rxrbln** [comment]
Due to cross compile incompleteness, we do not ship Perl on the binary ISOs by default. You need to install at least Perl for local software development: https://t2sde.org/kb/8/

**Comment by eneiasramos** [comment]
@rxrbln perfect my dear! I'll try to compile the source code... Thank you!
