### ISSUE TITLE
Cross compile make

### ISSUE THREAD

**Issue by rxrbln** [rxrbln/t2sde#6]
As cmake takes rather long to compile, it would be nice to be able to cross compile it to have it at hand for slower, vintage or retro system to compile smaller packages requiring make.

**Comment by lenticularis39** [comment]
I thought cmake does cross compile, maybe that was with some local changes I forgot to send a patch for - I'll check.

**Comment by lenticularis39** [comment]
Found it, disabling bootstrapping while cross compiling (i.e. using stage 0 cmake to build cross cmake) does the trick:

[cross-cmake.patch.txt](https://github.com/rxrbln/t2sde/files/6895390/cross-cmake.patch.txt)

**Comment by rxrbln** [comment]
Committed revision 52856.
