### ISSUE TITLE
Kernel without modules is not detected by T2 scripts

### ISSUE THREAD

**Issue by lenticularis39** [rxrbln/t2sde#61]
When building a kernel without modules (CONFIG_MODULES=n), T2 doesn't see it in isofs and initrd generation phases (scripts in `target/share`), because it uses the module directories to iterate installed kernels.

I believe this should be changed to something more reliable, e.g. kconfig files.

**Comment by rxrbln** [comment]
fixed with r54439, r54445 and r54446
