### ISSUE TITLE
Build-Target attempts to build gcc before building isl in stage 0

### ISSUE THREAD

**Issue by TechdudeGames** [rxrbln/t2sde#62]
Hello,
I'm currently trying to build T2 for the Intel Pentium III, and I noticed that the build script seems to try to build GCC before isl is built. On my machine this causes the GCC build to error out as it can't find isl. To fix this I have been using ./scripts/Build-Target -job 0-isl, and then restarting the regular build cycle. 

My build environment:
CPU: 2x Intel Xeon x5672
RAM: 24 GB DDR3
OS: Ubuntu 20.04.3

I am unsure if part of the problem is that I'm not building on T2, since if T2 shipped with isl the GCC build would find that version, but I just thought I would bring it to attention.

**Comment by rxrbln** [comment]
thanks for the report. While it sounds simple and logical, fixing it was noted rather opened an huge can of worms of improving our from scratch Canadian cross gcc bootstrap. Committed revision 54730. but still need to fix some gcc cross bootstrap libc++ location regression. Sigh. :-/
