### ISSUE TITLE
Remove libxfce4menu and libxfcegui4?

### ISSUE THREAD

**Issue by lenticularis39** [rxrbln/t2sde#65]
These packages need GTK+2 to install (Xfce uses GTK+3 now) and were replaced with garcon and libxfce4ui.

**Comment by lenticularis39** [comment]
Also the same with depracated xfce-utils-

**Comment by rxrbln** [comment]
sound good to me ;-)

**Comment by lenticularis39** [comment]
Commited revision 54783 and 54784.
