### ISSUE TITLE
Package docker packages

### ISSUE THREAD

**Issue by rxrbln** [rxrbln/t2sde#88]
https://github.com/docker

**Comment by janithcooray** [comment]
# Update

Build System
```
Linux t2 6.4.4-t2
```

Got the docker daemon ( moby / same thing they do at arch ) to build 
but encountered some issue running. related to [this issue](https://github.com/docker/cli/issues/2104)

Dependencies -
```
containerd
build-essentials ( general GNU )
go
-> runc module
git
libseccomp
systemd (instead of using cgroupfs)
python3+
-> jinja2 module
```

https://github.com/mk-fg/cgroup-tools

Issue - Unable to mount cgroupfs, after some lookups, seems it's not required if systemd is active. have some build errors when trying to build systemd. will keep looking 

The rest of the docker tools are Fully Open Source

Screenshots:

Docker D
![2023-10-28-16-51-55-540-min](https://github.com/rxrbln/t2sde/assets/50979590/f7ad96f2-7307-49a6-91b2-2b62cb73797a)


Startup Error

![2023-10-28-16-52-20-686-min](https://github.com/rxrbln/t2sde/assets/50979590/3ff8920d-6a88-4872-ba5b-e1990d567019)

**Comment by N0T4G** [comment]
Added `CONFIG_CGROUP_BPF` which fixed the issue.
I think the issue can be closed now as things seems to be working (at least for basic, one container usage).
