### ISSUE TITLE
gobject-introspection 1.70.0 doctemplates bug

### ISSUE THREAD

**Issue by TechdudeGames** [rxrbln/t2sde#92]
The current version of gobject-introspection currently has a bug in the configuration stage where it claims that the file doctemplates does not exist:

> giscanner/meson.build:58:0: ERROR: File doctemplates does not exist.

This is actually an issue with [gobject-introspection 1.70.0](https://gitlab.gnome.org/GNOME/gobject-introspection/-/issues/414), but it was resolved by 1.71.0. I updated the package via `./scripts/Update-Pkg`, and the build succeeds. 

My build env (on a qemu VM):
OS: T2 SDE 21.11 (2021/11/30)
CPU: Xeon X5672  (14 cores for the VM)
MEM: 16GB

**Comment by rxrbln** [comment]
thanks for the report, our data update bot updated this in the meantime:
r56124 | data | 2022-03-20 23:09:52 +0100 (Sun, 20 Mar 2022) | 2 lines
        * updated gobject-introspection (1.70.0 -> 1.72.0)
